# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-01 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20170701_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='updated',
            new_name='update',
        ),
    ]
