# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-01 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20170701_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='update',
            new_name='updated',
        ),
    ]
