# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20170703_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
